#!/bin/sh
#
# PROVIDE: psud
# BEFORE: sysctl

. /etc/rc.subr

name="psud"
desc="SMART PSU Daemon"                 
start_cmd="psud_start" 
stop_cmd=":"
rcvar="psud_enable"

psud_start () 
{
        /usr/local/bin/psud
}

load_rc_config $name
run_rc_command "$1"
