#
#  $Id$
# 
CC	= cc
PROG	= psud
SRCS	!= ls *c
OSNAME	!= uname
ARCH	!= uname -m
CFLAGS	= -O2 -Wall 
LDFLAGS	= -lgpio

MK_MAN	= no
MK_DEBUG_FILES = no

DESTDIR = /usr/local/bin

clean:
	@rm -f  *.o $(PROG) *debug *full .depend*

.include <bsd.prog.mk>
