#!/bin/sh
#
# PROVIDE: psud
# REQUIRE: syslogd
# BEFORE: DAEMON

. /etc/rc.subr

name="psud"
desc="Smart PSU Daemon"                 
rcvar="psud_enable"
command="/usr/local/bin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
